### ISSUE TITLE
CUDA ERROR

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1189]
I don't know what happened but yesterday I could type "using Oceananigans" after starting julia --project and it worked fine.  This morning, after a software update on ubuntu, now I'm getting a CUDA ERROR.  See below.

Any ideas what I can do to try and fix this?

```
julia> using Oceananigans
┌ Warning: Recursion during initialization of CUDA.jl
└ @ CUDA ~/.julia/packages/CUDA/0p5fn/src/initialization.jl:41
┌ Error: Could not initialize CUDA
│   exception =
│    CUDA error (code 803, CUDA_ERROR_SYSTEM_DRIVER_MISMATCH)
│    Stacktrace:
│     [1] throw_api_error(::CUDA.cudaError_enum) at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/cudadrv/error.jl:97
│     [2] __configure__(::Bool) at /home/fpoulin/.julia/packages/CUDA/0p5fn/src/initialization.jl:98
│     [3] macro expansion at /home/fpoulin/.julia/packages/CUDA/0p5fn/src/initialization.jl:29 [inlined]
│     [4] macro expansion at ./lock.jl:183 [inlined]
│     [5] _functional(::Bool) at /home/fpoulin/.julia/packages/CUDA/0p5fn/src/initialization.jl:26
│     [6] functional(::Bool) at /home/fpoulin/.julia/packages/CUDA/0p5fn/src/initialization.jl:19
│     [7] libcuda() at /home/fpoulin/.julia/packages/CUDA/0p5fn/src/initialization.jl:50
│     [8] (::CUDA.var"#697#cache_fptr!#11")() at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/utils/call.jl:31
│     [9] macro expansion at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/utils/call.jl:39 [inlined]
│     [10] macro expansion at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/cudadrv/libcuda.jl:35 [inlined]
│     [11] macro expansion at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/cudadrv/error.jl:102 [inlined]
│     [12] cuDeviceGetCount(::Base.RefValue{Int32}) at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/utils/call.jl:93
│     [13] length at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/cudadrv/devices.jl:111 [inlined]
│     [14] iterate at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/cudadrv/devices.jl:106 [inlined] (repeats 2 times)
│     [15] iterate at ./iterators.jl:139 [inlined]
│     [16] iterate at ./iterators.jl:138 [inlined]
│     [17] __init__() at /home/fpoulin/software/Oceananigans.jl/src/Oceananigans.jl:178
│     [18] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697
│     [19] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:782
│     [20] _require(::Base.PkgId) at ./loading.jl:1007
│     [21] require(::Base.PkgId) at ./loading.jl:928
│     [22] require(::Module, ::Symbol) at ./loading.jl:923
│     [23] eval(::Module, ::Any) at ./boot.jl:331
│     [24] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:134
│     [25] repl_backend_loop(::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:195
│     [26] start_repl_backend(::REPL.REPLBackend, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:180
│     [27] run_repl(::REPL.AbstractREPL, ::Any; backend_on_current_task::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:292
│     [28] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288
│     [29] (::Base.var"#807#809"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:399
│     [30] #invokelatest#1 at ./essentials.jl:710 [inlined]
│     [31] invokelatest at ./essentials.jl:709 [inlined]
│     [32] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:383
│     [33] exec_options(::Base.JLOptions) at ./client.jl:313
│     [34] _start() at ./client.jl:506
└ @ CUDA ~/.julia/packages/CUDA/0p5fn/src/initialization.jl:101
ERROR: InitError: CUDA.jl did not successfully initialize, and is not usable.
If you did not see any other error message, try again in a new session
with the JULIA_DEBUG environment variable set to 'CUDA'.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] libcuda() at /home/fpoulin/.julia/packages/CUDA/0p5fn/src/initialization.jl:51
 [3] (::CUDA.var"#697#cache_fptr!#11")() at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/utils/call.jl:31
 [4] macro expansion at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/utils/call.jl:39 [inlined]
 [5] macro expansion at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/cudadrv/libcuda.jl:35 [inlined]
 [6] macro expansion at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/cudadrv/error.jl:102 [inlined]
 [7] cuDeviceGetCount(::Base.RefValue{Int32}) at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/utils/call.jl:93
 [8] length at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/cudadrv/devices.jl:111 [inlined]
 [9] iterate at /home/fpoulin/.julia/packages/CUDA/0p5fn/lib/cudadrv/devices.jl:106 [inlined] (repeats 2 times)
 [10] iterate at ./iterators.jl:139 [inlined]
 [11] iterate at ./iterators.jl:138 [inlined]
 [12] __init__() at /home/fpoulin/software/Oceananigans.jl/src/Oceananigans.jl:178
 [13] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697
 [14] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:782
 [15] _require(::Base.PkgId) at ./loading.jl:1007
 [16] require(::Base.PkgId) at ./loading.jl:928
 [17] require(::Module, ::Symbol) at ./loading.jl:923
during initialization of module Oceananigans

**Comment by vchuravy** [comment]
> after a software update on ubuntu,

Did you reboot in between?

**Comment by francispoulin** [comment]
No, I did not but I will do that now.  Thanks @vchuravy for the suggestion and hope that does the trick

**Comment by francispoulin** [comment]
Just to confirm that yes, that did the trick.  It would appear that a few things needed to be downloaded.  Now they are and things are running as normal.  Thank you again @vchuravy for the help!

```
Downloading artifact: CUDA111
Downloading artifact: CUDNN_CUDA111
Downloading artifact: CUTENSOR_CUDA111
